image:
  repository: 11notes/netbird
  tag: "0.76.1"
  pullPolicy: IfNotPresent

replicaCount: 1
nameOverride: ""
fullnameOverride: ""
timezone: "Europe/Zurich"

netbird:
  fqdn: "ztna.domain.com"

postgres:
  serviceName: "postgres"
  existingSecret: ""
  existingSecretKey: "POSTGRES_PASSWORD"

extraEnv: []

service:
  type: ClusterIP
  grpcPort: 8080
  stunPort: 3478
  annotations: {}

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podLabels: {}

tmpfs:
  tmp:
    sizeLimit: ""

persistence:
  etc:
    enabled: true
    existingClaim: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 16Mi

  var:
    enabled: true
    existingClaim: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 2Gi

startupProbe:
  exec:
    command:
      - localhealth
      - http://127.0.0.1:9090/metrics
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 12

readinessProbe:
  exec:
    command:
      - localhealth
      - http://127.0.0.1:9090/metrics
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe:
  exec:
    command:
      - localhealth
      - http://127.0.0.1:9000/health
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6